name: Auto Sync Sheets

on:
  schedule:
    - cron: "*/10 * * * *"   # chạy mỗi 10 phút
  workflow_dispatch:

jobs:
  run-colab:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run Colab notebook
        uses: lamlamlam/colab-action@v1.0
        with:
          notebook: GoogleSheets_AutoSync.ipynb
